services:
  - type: web
    name: portfolio
    runtime: static
    buildCommand: ""
    staticPublishPath: public
    routes:
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /experience
        destination: /experience.html
      - type: rewrite
        source: /blog
        destination: /blog.html
      - type: rewrite
        source: /contact
        destination: /contact.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /src/css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /src/js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.html
        name: Cache-Control
        value: public, max-age=3600