services:
  - type: web
    name: portfolio
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: ./public
    routes:
      # Handle SPA routing - redirect all routes to index.html
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /blog
        destination: /blog.html
      - type: rewrite
        source: /contact
        destination: /contact.html
      - type: rewrite
        source: /experience
        destination: /experience.html
      - type: rewrite
        source: /home
        destination: /home.html
      - type: rewrite
        source: /
        destination: /index.html
    headers:
      # Security headers
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      # Cache static assets
      - path: /src/css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /src/js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Cache HTML files for shorter time
      - path: /*.html
        name: Cache-Control
        value: public, max-age=3600
    envVars:
      - key: NODE_ENV
        value: production