name: Pre-commit

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: make install
      - run: make precommit